version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${user_password}
      MYSQL_ROOT_PASSWORD: ${root_password}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/:/etc/my.cnf
    networks:
      mysql:

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer_container
    depends_on:
      - db
    ports:
      - '5050:8080'
    networks:
      mysql:

networks:
  mysql:
