version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${user_password}
      MYSQL_ROOT_PASSWORD: ${root_password}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      mysql:

  adminer:
    image: adminer
    restart: always
    container_name: adminer_container
    depends_on:
      - db
    ports:
      - '5050:8080'
    volumes:
       - ./adminer:/var/lib/pgadmin
    networks:
      mysql:

  python_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./db_app:/app
    networks:
      mysql:

networks:
  mysql:
